import { Urbanist } from "next/font/google";
import { Metadata } from "next";
import React from "react";
import "./globals.css";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "700"], // You can specify the weights you need
});

export const metadata: Metadata = {
  title: "POPULA",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={urbanist.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
